"""Backend-Vertraege der Plattform-Schicht (siehe PORTING.md, Abschnitt 2).

Die Protocols dokumentieren, was ein Plattform-Backend liefern muss. Die
Signaturen sind aus den ECHTEN Call-Sites in main.py/web abgeleitet - wer
ein neues Backend (darwin) schreibt, implementiert exakt diese Flaechen.
Windows erfuellt sie in localflow/platform/win32/.
"""

from typing import Callable, Optional, Protocol

# win32: HWND; darwin (geplant): pid des Zielprozesses
WindowTarget = Optional[int]


class PttHook(Protocol):
    """Gedrueckt/Losgelassen-Erkennung fuer EINE Hotkey-Kombination."""

    def start(self) -> None: ...
    def stop(self) -> None: ...


class Injector(Protocol):
    """Text-Paste + synthetische Tasten ins Zielfenster."""

    PASTE_OK: str
    PASTE_CLIPBOARD_ONLY: str
    PASTE_FAILED: str

    def get_foreground_hwnd(self) -> WindowTarget: ...
    def get_active_app(self) -> tuple[str, str]: ...
    def paste_text(self, text: str, restore_delay: float = 1.0,
                   target_hwnd: WindowTarget = None) -> str: ...
    def press_keys(self, keys: list[str], target_hwnd: WindowTarget = None,
                   gap: float = 0.04) -> None: ...


class Ducker(Protocol):
    duck_volume: float
    mute_complete_ts: float
    did_mute_sessions: int      # 0 => Head-Trim deaktiviert sich selbst

    def duck(self) -> None: ...
    def restore(self) -> None: ...


class OverlayBackend(Protocol):
    """Queue-basiert; alle Methoden aus beliebigen Threads aufrufbar."""

    def start(self) -> None: ...
    def set_state(self, state: str) -> None: ...
    def set_level(self, level: float) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_glass(self, enabled: bool) -> None: ...
    def set_style(self, font_family: str | None,
                  font_size: int | None) -> None: ...
    def set_theme(self, theme: str) -> None: ...


class SoundBackend(Protocol):
    def ensure_sounds(self) -> None: ...
    def play(self, name: str) -> None: ...


class AutostartBackend(Protocol):
    def is_enabled(self) -> bool: ...
    def set_enabled(self, enabled: bool) -> None: ...


class AppIntegration(Protocol):
    def acquire_single_instance(self) -> bool: ...
    def ensure_launcher_shortcut(self) -> None: ...
    def set_dpi_awareness(self) -> None: ...


class HotkeyBackend(Protocol):
    def make_ptt(self, combo: str, controller, swallow_mouse: bool = False) -> PttHook: ...
    def add_hotkey(self, combo: str, callback: Callable[[], None]) -> object: ...
    def remove_hotkey(self, handle: object) -> None: ...
    def capture_combo(self, timeout: float = 10.0) -> str | None: ...
